name: Java and Lua CI with Gradle

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch: # Allows manual runs

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read # Permission to read the repository contents
      id-token: write # If you need to create an access token (if interacting with private repositories, etc.)
      packages: write # Permission to write packages if needed for publishing
      actions: read # Permission to read actions in case you need to access other GitHub Actions resources

    steps:
    # Step 1: Checkout the repository
    - uses: actions/checkout@v4

    # Step 2: Set up JDK
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    # Step 3: Configure Gradle
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

    # Step 4: Install build tools for Lua
    - name: Install Lua dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y lua5.3 luarocks # Adjust Lua version as needed
        luarocks install luajit --local
        
    # Step 5: Build Java and Lua project
    - name: Build with Gradle
      run: ./gradlew build

    # Step 6: Optional Lua integration test
    - name: Test Lua integration
      run: |
        lua path/to/your/script.lua

  dependency-submission:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Permission to modify repository contents if you're pushing dependency data

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    # Submit dependency graph for alerts
    - name: Generate and submit dependency graph
      uses: gradle/actions/dependency-submission@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0
