name: Build and Publish Library

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Build environment
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake ninja-build
      continue-on-error: true # Allow workflow to continue if dependency installation fails

    - name: Build with CMake
      run: |
        mkdir build
        cd build
        cmake .. -G Ninja
        ninja
      continue-on-error: true # Allow workflow to continue if build fails

    - name: Upload Artifacts (if build successful)
      if: success()
      uses: actions/upload-artifact@v3
      with:
        name: library
        path: build/lib/*.so
