name: Build Lumos-X

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Java environment
      uses: actions/setup-java@v3
      with:
        java-version: '17' # Adjust according to your project's requirements

    - name: Install build tools
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential openjdk-17-jdk android-sdk

    - name: Build Lumos-X
      run: |
        ./gradlew build

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: lumos-x-build
        path: build/libs/
